# AUTOMATIC-STARTUP ***********************************************************
# *****************************************************************************
# Available commands: https://nikitabobko.github.io/AeroSpace/commands

start-at-login = true
after-login-command = [ # called when user logs into system
]
after-startup-command = [ # called when aerospace launches
    "exec-and-forget borders",

    # we use sleep to ensure the windows load order paints each workspace left
    # to right
    "exec-and-forget sleep 0 && open -a '/Applications/Microsoft Outlook.app'",
    "exec-and-forget sleep 0 && open -a '/Applications/Zen Browser.app'",
    "exec-and-forget sleep 0 && open -a '/Applications/Slack.app'",
    "exec-and-forget sleep 3 && open -a /Applications/WezTerm.app",
    "exec-and-forget sleep 3 && open -a /Applications/ForkLift.app",
    "exec-and-forget sleep 3 && open -a /Applications/Discord.app",
    "exec-and-forget sleep 6 && open -a /Applications/Obsidian.app",

    # automatically move windows around
    "exec-and-forget sleep 7 && aerospace move right --window-id $(aerospace list-windows --all | grep -i Slack | awk '{print $1}')",

    # disabled due to weird center-window snapping that would yank the mouse
    # to a previous window pane
    #    "exec-and-forget open -a '/Applications/AutoRaise.app'"
]

# LAYOUT **********************************************************************
# *****************************************************************************
# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping

enable-normalization-flatten-containers                         = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout      = 'tiles' # tiles|accordion
default-root-container-orientation = 'auto' # horizontal|vertical|auto
key-mapping.preset                 = 'qwerty' # qwerty|dvorak

# BEHAVIOR ********************************************************************
# *****************************************************************************
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse

automatically-unhide-macos-hidden-apps = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed           = ["move-mouse window-lazy-center"]

# PADDING *********************************************************************
# *****************************************************************************

accordion-padding = 30
[gaps]
inner.horizontal  = 20
inner.vertical    = 20
outer.left        = 20
outer.bottom      = 20
outer.top         = 20
outer.right       = 20




# *****************************************************************************
[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right
# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands
# *****************************************************************************




# FOCUS CHANGE KEYMAPS (cmd) **************************************************
# *****************************************************************************
# See: https://nikitabobko.github.io/AeroSpace/commands#focus
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace

# window panes **********************************

# vim-style
#cmd-h     = 'focus left'
#cmd-j     = 'focus down'
#cmd-k     = 'focus up'
#cmd-l     = 'focus right'
# arrow-style
cmd-left  = 'focus left'
cmd-down  = 'focus down'
cmd-up    = 'focus up'
cmd-right = 'focus right'

# workspaces ************************************

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'

# MOVEMENT KEYMAPS (cmd+shift) ************************************************
# *****************************************************************************
# See: https://nikitabobko.github.io/AeroSpace/commands#move
# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace

# window panes **********************************

# vim-style
#cmd-shift-h     = 'move left'
#cmd-shift-j     = 'move down'
#cmd-shift-k     = 'move up'
#cmd-shift-l     = 'move right'
# arrow-style
cmd-shift-left  = 'move left'
cmd-shift-down  = 'move down'
cmd-shift-up    = 'move up'
cmd-shift-right = 'move right'

# workspaces ************************************

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'

# JOIN KEYMAPS (cmd+ctrl) *****************************************************
# *****************************************************************************

# vim-style
# cmd-ctrl-h     = ['join-with left',  'mode main']
# cmd-ctrl-j     = ['join-with down',  'mode main']
# cmd-ctrl-k     = ['join-with up',    'mode main']
# cmd-ctrl-l     = ['join-with right', 'mode main']
# arrow-style
cmd-ctrl-left  = ['join-with left',  'mode main']
cmd-ctrl-down  = ['join-with down',  'mode main']
cmd-ctrl-up    = ['join-with up',    'mode main']
cmd-ctrl-right = ['join-with right', 'mode main']

# RESIZE KEYMAPS (cmd+alt) ****************************************************
# *****************************************************************************
# See: https://nikitabobko.github.io/AeroSpace/commands#resize
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor

cmd-alt-left  = 'resize smart -50'
cmd-alt-down  = 'resize smart -50'
cmd-alt-up    = 'resize smart +50'
cmd-alt-right = 'resize smart +50'

# MISC KEYMAPS ****************************************************************
# *****************************************************************************
# See: https://nikitabobko.github.io/AeroSpace/commands#mode
# See: https://nikitabobko.github.io/AeroSpace/commands#layout

# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'
alt-slash     = 'layout tiles horizontal vertical'
alt-comma     = 'layout accordion horizontal vertical'
alt-tab       = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
cmd-ctrl-f    = 'fullscreen'
cmd-ctrl-s    = 'mode service'

# SERVICE MODE KEYMAPS ********************************************************
# *****************************************************************************
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes

[mode.service.binding]
esc       = ['reload-config',                 'mode main']
r         = ['flatten-workspace-tree',        'mode main'] # reset
f         = ['layout floating tiling',        'mode main'] # floating
backspace = ['close-all-windows-but-current', 'mode main']

# WORKSPACES TO MONITORS ******************************************************
# *****************************************************************************

[workspace-to-monitor-force-assignment]
1 = ['studio display', 'main']
2 = ['secondary',      'main']
3 = ['g246hl',         'main']
4 = ['g246hl',         'main']

# AUTOMATIC APP WORKSPACE ASSIGNMENT ******************************************
# *****************************************************************************

# workspace 1 ***********************************

# zen browser
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
#if.during-aerospace-startup = true
#check-further-callbacks = true
run = ['move-node-to-workspace 1']

# wezterm
[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
#if.during-aerospace-startup = true
#check-further-callbacks = true
run = ['move-node-to-workspace 1']

# workspace 2 ***********************************

# slack
[[on-window-detected]]
if.app-id  = 'com.tinyspeck.slackmacgap'
#if.during-aerospace-startup = true
#check-further-callbacks = true
run = ['move-node-to-workspace 2']

# obsidian
[[on-window-detected]]
if.app-id  = 'md.obsidian'
#if.during-aerospace-startup = true
#check-further-callbacks = true
run = ['move-node-to-workspace 2']

# discord
[[on-window-detected]]
if.app-id  = 'com.hnc.Discord'
#if.during-aerospace-startup = true
#check-further-callbacks = true
run = ['move-node-to-workspace 2']

# workspace 3 ***********************************

# outlook
[[on-window-detected]]
if.app-id  = 'com.microsoft.Outlook'
#if.during-aerospace-startup = true
#check-further-callbacks = true
run = ['move-node-to-workspace 3']

# forklift
[[on-window-detected]]
if.app-id  = 'com.binarynights.ForkLift'
#if.during-aerospace-startup = true
#check-further-callbacks = true
run = ['move-node-to-workspace 3']

